### ISSUE TITLE
Would like a different hover color for light and dark mode

### ISSUE THREAD

**Issue by jswift24** [app-generator/django-dashboard-dattaable#43]
Currently they are the same.

**Comment by jswift24** [comment]
![image](https://github.com/user-attachments/assets/7cc1f0a3-252d-41b1-b1ff-8a640b5b7474)
![image](https://github.com/user-attachments/assets/cd025313-fe4e-4c0d-8395-07d8d119713b)

**Comment by mominur-helios** [comment]
Hello @jswift24 ,

Change the hover color for dark mode by using class `.dark`
```
.dark li:hover {
    /**/
}
```

and for light mode, simply use
```
li:hover {
    /**/
}
```

Thank you!
